// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ChainCrims.DataBase;

namespace ChainCrims.Migrations
{
    [DbContext(typeof(ChainCrimsContext))]
    [Migration("20211028002050_added")]
    partial class added
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("ChainCrims.Models.Arma", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool?>("Banido")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("Criacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("IdBlockchain")
                        .HasColumnType("integer");

                    b.Property<int?>("IdConta")
                        .HasColumnType("integer");

                    b.Property<int?>("IdSuspeito")
                        .HasColumnType("integer");

                    b.Property<string>("Imagem")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<float?>("Poder")
                        .HasColumnType("real");

                    b.Property<bool?>("Queimado")
                        .HasColumnType("boolean");

                    b.Property<int?>("Saude")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdConta");

                    b.ToTable("Armas");
                });

            modelBuilder.Entity("ChainCrims.Models.Bonus", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Descriacao")
                        .HasColumnType("text");

                    b.Property<int?>("DuracaoMax")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("ValorBonus")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Bonus");
                });

            modelBuilder.Entity("ChainCrims.Models.Conta", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool?>("Banido")
                        .HasColumnType("boolean");

                    b.Property<string>("Carteira")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Criacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("HashSenha")
                        .HasColumnType("text");

                    b.Property<double?>("Saldo")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("UltimoLogin")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UltimoSaque")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Contas");
                });

            modelBuilder.Entity("ChainCrims.Models.Registro", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("Acao")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Criacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("IdConta")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdConta");

                    b.ToTable("Registros");
                });

            modelBuilder.Entity("ChainCrims.Models.RegistroArma", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("IdArma")
                        .HasColumnType("integer");

                    b.Property<int?>("IdContaPara")
                        .HasColumnType("integer");

                    b.Property<int?>("RegistroId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RegistroId");

                    b.ToTable("RegistroArmas");
                });

            modelBuilder.Entity("ChainCrims.Models.RegistroSuspeito", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("IdContaPara")
                        .HasColumnType("integer");

                    b.Property<int?>("IdSuspeito")
                        .HasColumnType("integer");

                    b.Property<int?>("RegistroId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RegistroId");

                    b.ToTable("RegistroSuspeitos");
                });

            modelBuilder.Entity("ChainCrims.Models.ResultadoRoubo", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("IdRoubo")
                        .HasColumnType("integer");

                    b.Property<int?>("IdSuspeito")
                        .HasColumnType("integer");

                    b.Property<double?>("Respeito")
                        .HasColumnType("double precision");

                    b.Property<string>("Resultado")
                        .HasColumnType("text");

                    b.Property<int?>("RouboId")
                        .HasColumnType("integer");

                    b.Property<double?>("Saldo")
                        .HasColumnType("double precision");

                    b.Property<int?>("SuspeitoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RouboId");

                    b.HasIndex("SuspeitoId");

                    b.ToTable("ResultadoRoubos");
                });

            modelBuilder.Entity("ChainCrims.Models.Roubo", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<float?>("ChanceBase")
                        .HasColumnType("real");

                    b.Property<string>("Descriacao")
                        .HasColumnType("text");

                    b.Property<string>("Imagem")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<int?>("PoderMin")
                        .HasColumnType("integer");

                    b.Property<float?>("RecompensaMax")
                        .HasColumnType("real");

                    b.Property<float?>("RecompensaMin")
                        .HasColumnType("real");

                    b.Property<float?>("RespeitoMax")
                        .HasColumnType("real");

                    b.Property<float?>("RespeitoMin")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Roubos");
                });

            modelBuilder.Entity("ChainCrims.Models.Suspeito", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool?>("Banido")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("Criacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Estamina")
                        .HasColumnType("integer");

                    b.Property<List<int>>("Habilidades")
                        .HasColumnType("integer[]");

                    b.Property<int?>("IdArma")
                        .HasColumnType("integer");

                    b.Property<int?>("IdBlockchain")
                        .HasColumnType("integer");

                    b.Property<int?>("IdConta")
                        .HasColumnType("integer");

                    b.Property<string>("Imagem")
                        .HasColumnType("text");

                    b.Property<int?>("Nivel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<float?>("Poder")
                        .HasColumnType("real");

                    b.Property<DateTime?>("ProximaRecarga")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("Queimado")
                        .HasColumnType("boolean");

                    b.Property<double?>("Respeito")
                        .HasColumnType("double precision");

                    b.Property<float?>("Saude")
                        .HasColumnType("real");

                    b.Property<string>("Titulo")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UltimaLuta")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdArma")
                        .IsUnique();

                    b.HasIndex("IdConta");

                    b.ToTable("Suspeitos");
                });

            modelBuilder.Entity("ChainCrims.Models.SuspeitoBonus", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime?>("Criacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Duracao")
                        .HasColumnType("integer");

                    b.Property<int?>("IdBonus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SuspeitoBonus");
                });

            modelBuilder.Entity("ChainCrims.Models.Transacao", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<double?>("Amount")
                        .HasColumnType("double precision");

                    b.Property<long?>("BlockHeight")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("BlockTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Receiver")
                        .HasColumnType("text");

                    b.Property<string>("Sender")
                        .HasColumnType("text");

                    b.Property<bool?>("Status")
                        .HasColumnType("boolean");

                    b.Property<string>("Symbol")
                        .HasColumnType("text");

                    b.Property<string>("Tx")
                        .HasColumnType("text");

                    b.Property<int?>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Transacoes");
                });

            modelBuilder.Entity("ChainCrims.Models.Arma", b =>
                {
                    b.HasOne("ChainCrims.Models.Conta", "Dono")
                        .WithMany("Armas")
                        .HasForeignKey("IdConta");

                    b.Navigation("Dono");
                });

            modelBuilder.Entity("ChainCrims.Models.Registro", b =>
                {
                    b.HasOne("ChainCrims.Models.Conta", null)
                        .WithMany("Registros")
                        .HasForeignKey("IdConta");
                });

            modelBuilder.Entity("ChainCrims.Models.RegistroArma", b =>
                {
                    b.HasOne("ChainCrims.Models.Registro", null)
                        .WithMany("RegistroArmas")
                        .HasForeignKey("RegistroId");
                });

            modelBuilder.Entity("ChainCrims.Models.RegistroSuspeito", b =>
                {
                    b.HasOne("ChainCrims.Models.Registro", null)
                        .WithMany("RegistroSuspeitos")
                        .HasForeignKey("RegistroId");
                });

            modelBuilder.Entity("ChainCrims.Models.ResultadoRoubo", b =>
                {
                    b.HasOne("ChainCrims.Models.Roubo", "Roubo")
                        .WithMany()
                        .HasForeignKey("RouboId");

                    b.HasOne("ChainCrims.Models.Suspeito", "Suspeito")
                        .WithMany()
                        .HasForeignKey("SuspeitoId");

                    b.Navigation("Roubo");

                    b.Navigation("Suspeito");
                });

            modelBuilder.Entity("ChainCrims.Models.Suspeito", b =>
                {
                    b.HasOne("ChainCrims.Models.Arma", "Arma")
                        .WithOne("Suspeito")
                        .HasForeignKey("ChainCrims.Models.Suspeito", "IdArma");

                    b.HasOne("ChainCrims.Models.Conta", "Dono")
                        .WithMany("Suspeitos")
                        .HasForeignKey("IdConta");

                    b.Navigation("Arma");

                    b.Navigation("Dono");
                });

            modelBuilder.Entity("ChainCrims.Models.Arma", b =>
                {
                    b.Navigation("Suspeito");
                });

            modelBuilder.Entity("ChainCrims.Models.Conta", b =>
                {
                    b.Navigation("Armas");

                    b.Navigation("Registros");

                    b.Navigation("Suspeitos");
                });

            modelBuilder.Entity("ChainCrims.Models.Registro", b =>
                {
                    b.Navigation("RegistroArmas");

                    b.Navigation("RegistroSuspeitos");
                });
#pragma warning restore 612, 618
        }
    }
}
